### PR TITLE
Feature/timesheet dashboard

### PR DESCRIPTION
**Pull request by mihaisolomon**

### CODE REVIEW

**Comment by mihaisolomon** [comment]
@heloufir Take a look over this. That error should be gone.

**Comment by mihaisolomon** [comment]
Added a table instead of a view for the time logged 

image

**Comment by heloufir** [comment]
> Added a table instead of a view for the time logged
> 
> image

That looks better

**Comment by heloufir** [comment]
@mihaisolomon 
yep the first error is resolved, but I got another like I have said in the issue #29 

image

https://flareapp.io/share/Bm0BJyW7

I think the activity is null, and it need to be checked with a condition like below:

```php
foreach ($collection as $item) {
    if ($item->activity) { // <- HERE
        $datasets['sets'][] = $item->value;
        $datasets['labels'][] = $item->activity->name;
    } // <- HERE
}
```

**Pull request merged**
