### PR TITLE
Support for Docker #23

### PR DESCRIPTION
**Pull request by JaccoVE**
Started working on this since it was not there yet, in my case the following additions can successfully build a Docker image.

### CODE REVIEW

**Comment by heloufir** [comment]
That's awesome, I was planing to work on this the next week, I will check it ASAP and merge it.

**Comment by heloufir** [comment]
@JaccoVE I got this issue, when I run the buildDocker command 
I am using Docker on Windows with windows virtualization (not wsl), that happened to you?

And also, do you mind putting `devaslanphp/helper` instead of `jaccove/helper` so the name of the image stays the same as the repo, because I plan later to put some _Github actions_ to publish the repo directly on _Docker Hub_

image

**Comment by JaccoVE** [comment]
I didn’t have this issue, but I’m builder it on Linux. Looks like a line-ending error. Will look into it tomorrow and also fix the naming.

**Review by heloufir — CHANGES_REQUESTED** [review]
I changed the status so you can commit again when finished.
Thank you

**Comment by JaccoVE** [comment]
I noticed that Git changed the line endings back to CRLF instead of LF for the run.sh. This should be fixed now by the latest commit.

**Review by heloufir — CHANGES_REQUESTED** [review]
All works perfectly, but I needed to remove an extra space in the file `run.sh` to make it works, because I got some errors in the docker terminal, here is a screenshot:

image

And also I think in the file `buildDocker.sh` you can build only the latest I think, so we don't need for now to change the version everytime (or I make a mistake?)

image

**Comment by heloufir** [comment]
I made the changes just above, but if needed you can revert or change them.

**Comment by JaccoVE** [comment]
Didn't see the space error, but sounds good! Good to hear it works :)

I was indeed thinking about how to do the versioning, I agree it is annoying to update this tag number every time, but I do think it would be nice to add. Can't we grab the version number from Git like they do here for example:

[https://betterprogramming.pub/how-to-version-your-docker-images-1d5c577ebf54](https://betterprogramming.pub/how-to-version-your-docker-images-1d5c577ebf54)

**Comment by heloufir** [comment]
@JaccoVE I just released a new version with your dev (this PR), and also a github action `.github/workflows/docker-image.yml` where I did a trick to dynamically get the release tag and build an image based on this release.

And also you can check the docs section for the docker details: [https://devaslanphp.github.io/project-management/#/docker](https://devaslanphp.github.io/project-management/#/docker)

**Comment by JaccoVE** [comment]
Looks very good! Let me know when any changes are necessary.

**Pull request merged**
